image: alpine/edge
packages:
  - go
secrets:
  - a40eedbe-ea5a-474b-9971-cdcd9ff369e1
sources:
  - git@git.sr.ht:~dvko/gozer
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      cd gozer
      go get .
  - build: |
      cd gozer
      go build -v ./...
  - test: |
      cd gozer
      go test
  - github_mirror: |
      cd gozer
      git push git@github.com:dannyvankooten/gozer.git --mirror
